/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        Car garage = new Car("fusca", "branco", new Engine(52, 1500));
        ArrayList<Engine> stock = new ArrayList<>();
        stock.add(garage.getEngine());
        garage.setEngine(new Engine(70,2000));

        garage = new Car("uno", "branco", new Engine(52, 1500));

    }
}
