/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.products.Dimension;
import ads.poo.products.Phone;
import ads.poo.products.Wireless;

public class App {

    public static void main(String[] args) {
        Phone phone = new Phone(1, "1", "1", 100, new Dimension(10, 10, 10));
        Phone phoneWireless = new Wireless(1, "1", "1", 100, new Dimension(10, 10, 10), 1, 1, 1);

        System.out.println(phone);
        System.out.println(phoneWireless);

        int f = (int) 2.5;
        System.out.println(f);
    }

}
