/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        /*
        Buzz buzz = new Buzz();

        System.out.println(buzz.startLaser());

        System.out.println("Capacete aberto? " + buzz.getHelmet());


        Pen c = new Pen();

        System.out.println(c.draw());

        */

        Person person = new Person();

        person.setName("Eduardo");
        person.setCPF("123.456.789-10");
        person.setEmail("teste@gmail.com");

        System.out.println(person);



    }
}
