/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import ads.poo.products.Cellphone;
import ads.poo.products.Dimension;
import ads.poo.products.Phone;
import ads.poo.products.Wireless;

public class App {

    public static void main(String[] args) {
        /*
        Phone phone = new Phone(1, "1", "1", 100, new Dimension(10, 10, 10));
        Phone phoneWireless = new Wireless(1, "1", "1", 100, new Dimension(10, 10, 10), 1, 1, 1);

        System.out.println(phone);
        System.out.println(phoneWireless);

        int f = (int) 2.5;
        System.out.println(f);


        Phone p;
        Wireless w;
        Cellphone c;
        Cellphone d;

        p = new Cellphone(1, "1", "1", 100, new Dimension(10, 10, 10), "Android");
        c = new Cellphone(1, "1", "1", 100, new Dimension(10, 10, 10), "Android");

        d = (Cellphone) p;

         */

        Phone[] p = new Phone[4];

        p[0] = new Phone(1, "1", "1", 100, new Dimension(10, 10, 10));
        p[1] = new Cellphone(1, "1", "1", 100, new Dimension(10, 10, 10), "Android");
        p[2] = new Cellphone(1, "1", "1", 100, new Dimension(10, 10, 10), "Windows");
        p[3] = new Wireless(1, "1", "1", 100, new Dimension(10, 10, 10), 1, 1, 1);

        for (Phone phone : p) {
            System.out.println(phone);

            if (phone instanceof Cellphone) {
                System.out.println( ((Cellphone) phone).getOperationalSystem());
            }
        }


    }

}
