/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayDeque;

public class App {

    public static void main(String[] args) {
        Calc calc = new Calc();

        calc.adiciona_numero(1.0);
    }
}
