/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package heritage;

import org.checkerframework.checker.units.qual.A;

public class App {

    public static void main(String[] args) {

        Character villager = new Villager();
        Character archer = new Archer();
        Character knight = new Knight();

        villager.attack();
        archer.attack();
        knight.attack();
    }
}
