/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;
import java.util.HashMap;

public class App {

    public static void main(String[] args) {
        HashMap<String, Book> bd = new HashMap<>();

        Author maquiavel = new Author("Maquiavel", "Italiano");
        ArrayList<Author> authorsJava = new ArrayList<>();
        authorsJava.add(maquiavel);

        Book oPrincipe = new Book("123","O Príncipe", 50.00, authorsJava);

        bd.put(oPrincipe.getIsbn(), oPrincipe);

        Book l = bd.get("123");

        if( l != null){
            Author other = new Author("Other", "BR");
            l.addAuthor(other);
        }
    }
}
