/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class App {

    public static void main(String[] args) {

        // Proguard - Ofuscação

        //String currentDir = System.getProperty("user.dir");
        //Path path = Path.of(currentDir + "/arquivo.txt");

        // ./gradlew run --args "teste.txt"

        // Path path = Path.of(args[0]);

        /* System.out.println(path);

        if (Files.exists(path)) {
            System.out.println(String.format("Arquivo: %s", path.toAbsolutePath()));
            System.out.println(String.format("Regular: %s", Files.isRegularFile(path)));
            System.out.println(String.format("Diretório: %s", Files.isDirectory(path)));
            System.out.println(String.format("Permissão de leitura: %s", Files.isReadable(path)));
            System.out.println(String.format("Permissão de escrita: %s", Files.isWritable(path)));
        } else {
            System.out.println("Arquivo não encontrado");
        }

        */
    
        String currentDir = System.getProperty("user.dir");
        Path path = Path.of(currentDir + "/novo.txt");
        
        try {
            Files.createFile(path);
            System.out.println("Arquivo criado");

            Path novoPath = Path.of(currentDir + "/novo.txt");
            Files.move(path, novoPath);
            System.out.println("Arquivo atualizado");


            Files.deleteIfExists(novoPath);
            System.out.println("Arquivo deletado");
        } catch (Exception e) {
            System.err.println("Erro: " + e);
        }
    }

}
