/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayDeque;
import java.util.Deque;

public class App {

    public static void main(String[] args) {

        Deque<Carta> cartasBaralho = new ArrayDeque<>();

        for (Naipes n : Naipes.values()) {

            for (Cartas c : Cartas.values()) {
                cartasBaralho.add(new Carta(c, n));
            }
        }

        System.out.println(cartasBaralho.toString());
    }
}
